/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AssetObject, ContractClause, ContractSpec, LicensingTier } from '../types';

export class ContractGenerator {
  public static readonly CONTRACT_DISCLAIMER = 
    "Legal clauses are templates only. They require review by qualified counsel before use.";

  public static generateContracts(
    asset: AssetObject,
    tiers: LicensingTier[]
  ): Record<string, ContractSpec> {
    const savingsTier = tiers.find(t => t.royaltyModel === 'percentage_of_savings') || tiers[0];
    const oemTier = tiers.find(t => t.royaltyModel === 'per_device_oem') || tiers[2];

    const coreClauses: ContractClause[] = [
      {
        id: "clause-grant",
        title: "1. Commercial Grant of Rights & Scope",
        category: "Grant",
        summary: "Grants non-exclusive, worldwide commercial license to deploy and execute compiled asset binaries.",
        content: `Licensor hereby grants to Licensee a non-exclusive, non-transferable, worldwide commercial license to integrate, embed, execute, and run the Asset binaries ("${asset.name}") within Licensee's internal production cloud clusters, hardware nodes, and client-facing infrastructure.`,
        mandatory: true
      },
      {
        id: "clause-royalty-metric",
        title: "2. Royalty Calculation & Verification Telemetry",
        category: "Royalty",
        summary: "Establishes transparent royalty accounting based on verified compute cost reduction.",
        content: `Licensee shall pay Licensor an ongoing commercial royalty equal to ${savingsTier.rateDescription}, payable monthly in arrears. Net savings shall be verified via hardware cycle counters and monthly third-party cloud compute billing records.`,
        mandatory: true
      },
      {
        id: "clause-audit-rights",
        title: "3. Verification & Telemetry Safeguards",
        category: "Audit",
        summary: "Permits automated telemetry logging solely for reconciliation while safeguarding Licensee data privacy.",
        content: `Licensor may inspect automated telemetry logs generated by the software supervisor daemon solely to reconcile billed usage vs. reported node capacity. Licensor shall have zero access to Licensee customer data or unencrypted application payloads.`,
        mandatory: true
      },
      {
        id: "clause-ip-defensibility",
        title: "4. Trade Secret Protection & Reverse Engineering Ban",
        category: "IP Protection",
        summary: "Protects low-level assembly routines and lockless memory layouts under trade secret covenants.",
        content: `Licensee acknowledges that the processing manifold, internal state representations, and low-level kernel barriers constitute proprietary trade secrets under applicable trade secret statutes. Licensee covenants not to decompile, disassemble, or reverse engineer binary releases.`,
        mandatory: true
      },
      {
        id: "clause-indemnity",
        title: "5. Intellectual Property Indemnification",
        category: "Indemnity",
        summary: "Licensor warrants that no copyleft copyleft licenses were detected in non-forensic scans and provides standard copyright indemnity.",
        content: `Licensor warrants that, based on non-forensic AST scanning, the Asset is free from identified copyleft open-source contagion (GPL/AGPL) and shall defend, indemnify, and hold harmless Licensee against any third-party claims asserting copyright infringement arising from authorized usage of the Asset.`,
        mandatory: true
      },
      {
        id: "clause-termination",
        title: "6. Term, Invoicing & Orderly Transition",
        category: "Termination",
        summary: "12-month renewable term with 60-day cure period and orderly transition period.",
        content: `This Agreement shall remain in effect for an initial term of twelve (12) months. Upon material uncured breach or insolvency, the non-breaching party may terminate with thirty (30) days written notice. Upon termination, Licensee retains a 90-day grace period to migrate active production traffic.`,
        mandatory: false
      }
    ];

    const draftMarkdown = `# MASTER COMMERCIAL SOFTWARE & ROYALTY LICENSING AGREEMENT
> **DISCLAIMER**: ${ContractGenerator.CONTRACT_DISCLAIMER}
> This draft was generated by an automated contract template synthesizer. It does not constitute formal legal advice. Review with legal counsel is required.

**Asset Identifier:** ${asset.name} (${asset.id})  
**Governing Law:** State of Delaware, United States  
**Classification Kind:** ${asset.primarykind.toUpperCase()}  

---

### PREAMBLE
This Master Commercial Licensing Agreement (the "Agreement") is entered into by and between **Licensor** and **Licensee** (collectively, the "Parties").

### RECITALS
WHEREAS, Licensor is the author of software assets comprising **${asset.name}**, featuring ${asset.claims[0] || 'high-performance execution'}; and  
WHEREAS, Licensee desires to license and integrate said software into its enterprise production compute infrastructure;

---

## 1. GRANT OF LICENSE
${coreClauses[0].content}

## 2. ROYALTY STRUCTURE & MONETIZATION FORMULA
${coreClauses[1].content}

## 3. AUDIT & TELEMETRY VERIFICATION
${coreClauses[2].content}

## 4. INTELLECTUAL PROPERTY & TRADE SECRETS
${coreClauses[3].content}

## 5. INDEMNIFICATION & WARRANTIES
${coreClauses[4].content}

## 6. TERM & TERMINATION
${coreClauses[5].content}

---
**IN WITNESS WHEREOF**, the Parties hereto have caused this Agreement to be executed by their duly authorized representatives.

**FOR LICENSOR:** _________________________________  Date: _________  
**FOR LICENSEE:** _________________________________  Date: _________  
`;

    return {
      core_savings_agreement: {
        contractType: "Master Compute Savings Agreement (MLA)",
        title: `MLA: ${asset.name} Enterprise Value-Share`,
        clauses: coreClauses,
        fullDraftMarkdown: draftMarkdown
      },
      oem_hardware_agreement: {
        contractType: "OEM Embedded Hardware License",
        title: `OEM: ${asset.name} Device Firmware License`,
        clauses: [
          ...coreClauses.slice(0, 1),
          {
            id: "clause-oem-royalty",
            title: "2. Per-Device Royalty Schedule",
            category: "Royalty",
            summary: "Fixed per-device embedded fee for robotics and edge IoT hardware.",
            content: `Licensee shall pay an OEM unit royalty of ${oemTier.rateDescription} for each physical robot, AMR, or server board flashed with firmware incorporating the Asset binary image.`,
            mandatory: true
          },
          ...coreClauses.slice(2)
        ],
        fullDraftMarkdown: draftMarkdown.replace(
          "Master Commercial Software & Royalty Licensing Agreement",
          "OEM Embedded Hardware Firmware Royalty Agreement"
        )
      }
    };
  }
}
